[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/test"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "lesson-plan-generator"

[services.variables]
NODE_ENV = "production"
